# Generated by Django 2.2 on 2019-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='password',
            field=models.IntegerField(max_length=20),
        ),
    ]
